# Copyright (c) 2026 Alif Semiconductor
# SPDX-License-Identifier: Apache-2.0

# Spark turbo: HE core 240 MHz (from 160 MHz)
CONFIG_ALIF_SPARK_TURBO_MODE=y
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=240000000
